######################################################################
##
## Filename: Shift_and_Compare.udo
## Created on: Sun Nov 24 14:53:31 Střední Evropa (běžný čas) 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
